import { useEffect, useState, type ReactNode, type FormEvent } from 'react';

export function Result({ title, detail, onReplay }: { title: string; detail: string; onReplay: () => void }) {
  return <div className="result-banner"><h2>{title}</h2><p>{detail}</p><button className="button button-secondary button-small" onClick={onReplay} data-testid="button-replay">Play again ↻</button></div>;
}

function key(name: string) { return `gamebox-${name}`; }
function readNumber(name: string) { if (typeof window === 'undefined') return 0; try { const value = Number(localStorage.getItem(key(name)) || 0); return Number.isFinite(value) ? value : 0; } catch { return 0; } }
function saveNumber(name: string, value: number) { if (typeof window !== 'undefined') localStorage.setItem(key(name), String(value)); }
function readStats<T extends Record<string, number>>(name: string, fallback: T): T { if (typeof window === 'undefined') return fallback; try { const parsed = JSON.parse(localStorage.getItem(key(name)) || 'null'); return parsed && typeof parsed === 'object' ? { ...fallback, ...parsed } : fallback; } catch { return fallback; } }
function saveStats<T extends Record<string, number>>(name: string, stats: T) { if (typeof window !== 'undefined') localStorage.setItem(key(name), JSON.stringify(stats)); }

export function TicTacToe() {
  const fresh = () => Array<string | null>(9).fill(null);
  const [board, setBoard] = useState(fresh); const [turn, setTurn] = useState<'X'|'O'>('X'); const [result, setResult] = useState<'X'|'O'|'draw'|null>(null); const [scores,setScores]=useState(()=>readStats('ttt-scores',{X:0,O:0,draws:0}));
  const wins = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
  const winning = wins.find((line) => line.every((i) => board[i] === result && result !== 'draw')) || [];
  const reset = () => { setBoard(fresh()); setTurn('X'); setResult(null); };
  const play = (index: number) => { if (board[index] || result) return; const next = [...board]; next[index] = turn; const line = wins.find((combo) => combo.every((i) => next[i] === turn)); setBoard(next); if (line) { setResult(turn); setScores((current) => { const updated = { ...current, [turn]: current[turn] + 1 }; saveStats('ttt-scores',updated); return updated; }); } else if (next.every(Boolean)) { setResult('draw'); setScores((current) => { const updated = { ...current, draws: current.draws + 1 }; saveStats('ttt-scores',updated); return updated; }); } else setTurn(turn === 'X' ? 'O' : 'X'); };
  return <div>{result ? <Result title={result === 'draw' ? 'Dead even.' : `${result} takes it.`} detail={result === 'draw' ? 'Nobody blinked. Nobody won.' : `A clean line across the board. ${scores.X} X wins · ${scores.O} O wins.`} onReplay={reset} /> : <><div className="status-line">{turn} to move　·　X {scores.X}　·　O {scores.O}　·　Draws {scores.draws}</div><div className="ttt-board">{board.map((cell, i) => <button key={i} className={`ttt-cell ${cell === 'O' ? 'o' : ''} ${winning.includes(i) ? 'win' : ''}`} onClick={() => play(i)} aria-label={`Square ${i + 1}${cell ? `, ${cell}` : ''}`} disabled={Boolean(cell)} data-testid={`button-ttt-${i}`}>{cell}</button>)}</div></>}</div>;
}

const WORDS = ['CRANE','PIXEL','MUSIC','BRICK','SNAKE','GRAPE','LIGHT','BOARD','QUEST','CLOUD'];
function wordStatuses(guess: string, answer: string) { const statuses = Array<string>(5).fill('absent'); const remaining: Record<string, number> = {}; answer.split('').forEach((letter) => { remaining[letter] = (remaining[letter] || 0) + 1; }); guess.split('').forEach((letter, index) => { if (letter === answer[index]) { statuses[index] = 'correct'; remaining[letter] -= 1; } }); guess.split('').forEach((letter, index) => { if (statuses[index] === 'correct') return; if (remaining[letter] > 0) { statuses[index] = 'present'; remaining[letter] -= 1; } }); return statuses; }
export function Wordle() {
  const [answer, setAnswer] = useState(() => WORDS[Math.floor(Math.random() * WORDS.length)]); const [guesses, setGuesses] = useState<string[]>([]); const [input, setInput] = useState(''); const [message, setMessage] = useState(''); const done = guesses.includes(answer) || guesses.length >= 6;
  const reset = () => { setAnswer(WORDS[Math.floor(Math.random() * WORDS.length)]); setGuesses([]); setInput(''); setMessage(''); };
  const submit = () => { const guess = input.toUpperCase(); if (guess.length !== 5) { setMessage('Five letters, exactly.'); return; } if (guesses.includes(guess)) { setMessage('Already played.'); return; } setGuesses((g) => [...g, guess]); setInput(''); setMessage(''); };
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (done) return; if (/^[a-z]$/i.test(event.key) && input.length < 5) setInput((value) => value + event.key.toUpperCase()); if (event.key === 'Backspace') setInput((value) => value.slice(0,-1)); if (event.key === 'Enter') submit(); }; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey); });
  const keyboard = 'QWERTYUIOPASDFGHJKLZXCVBNM'.split('');
  const status = (letter: string) => { let best = ''; const rank: Record<string, number> = { absent: 1, present: 2, correct: 3 }; guesses.forEach((guess) => wordStatuses(guess,answer).forEach((state,index) => { if (guess[index] === letter && (rank[state] || 0) > (rank[best] || 0)) best = state; })); return best; };
  return <div className="wordle-wrap">{done ? <Result title={guesses.includes(answer) ? 'Nailed it.' : answer} detail={guesses.includes(answer) ? `${guesses.length} ${guesses.length === 1 ? 'guess' : 'guesses'} to find it.` : 'The word got away this time.'} onReplay={reset} /> : <><div className="wordle-board">{Array.from({length:6}).map((_, row) => <div className="wordle-row" key={row}>{Array.from({length:5}).map((__, col) => { const value = guesses[row]?.[col] || (row === guesses.length ? input[col] : ''); const states = guesses[row] ? wordStatuses(guesses[row],answer) : []; return <div className={`wordle-tile ${states[col] || ''}`} key={col}>{value}</div>; })}</div>)}</div><div className="status-line" style={{marginTop:'.8rem',color:'#ff8054'}}>{message}</div><div className="wordle-keyboard">{keyboard.map((letter) => <button key={letter} className={`wordle-key ${status(letter)}`} onClick={() => input.length < 5 && setInput((value) => value + letter)} data-testid={`button-wordle-${letter}`}>{letter}</button>)}<button className="wordle-key wide" onClick={() => setInput((value) => value.slice(0,-1))}>DEL</button><button className="wordle-key wide" onClick={submit}>ENTER</button></div></>}</div>;
}

type Edge = { h: boolean[][]; v: boolean[][] };
export function DotsBoxes() {
  const fresh = (): Edge => ({ h:Array.from({length:4},()=>Array(3).fill(false)), v:Array.from({length:3},()=>Array(4).fill(false)) });
  const [edges,setEdges] = useState(fresh); const [boxes,setBoxes] = useState(Array(9).fill('')); const [turn,setTurn] = useState<'A'|'B'>('A'); const [scores,setScores] = useState({A:0,B:0});
  const reset = () => {setEdges(fresh());setBoxes(Array(9).fill(''));setTurn('A');setScores({A:0,B:0});};
  const draw = (kind:'h'|'v', r:number, c:number) => { if (edges[kind][r][c] || boxes.every(Boolean)) return; const next = {h:edges.h.map((row)=>[...row]),v:edges.v.map((row)=>[...row])}; next[kind][r][c]=true; const claimed=[...boxes]; let did=false;
    for(let br=0;br<3;br++) for(let bc=0;bc<3;bc++){const i=br*3+bc; if(!claimed[i]&&next.h[br][bc]&&next.h[br+1][bc]&&next.v[br][bc]&&next.v[br][bc+1]){claimed[i]=turn;did=true;}}
    setEdges(next);setBoxes(claimed);if(did)setScores((s)=>({...s,[turn]:s[turn]+claimed.filter((v)=>v===turn).length-s[turn]}));else setTurn(turn==='A'?'B':'A');
  };
  const complete = boxes.every(Boolean); const winner = scores.A === scores.B ? 'Draw game.' : scores.A > scores.B ? 'You own the grid.' : 'The house takes it.';
  return <div className="dots-wrap">{complete ? <Result title={winner} detail={`${scores.A} to ${scores.B} squares.`} onReplay={reset} /> : <><div className="status-line">Your squares: {scores.A}　·　House: {scores.B}　·　{turn === 'A' ? 'your move' : 'house move'}</div><div className="dots-board">{Array.from({length:7}).map((_,r)=><div className="dots-row" key={r}>{Array.from({length:7}).map((__,c)=>{if(r%2===0&&c%2===0)return <span className="dot" key={c}/>;if(r%2===0)return <button key={c} className={`edge h ${edges.h[r/2][(c-1)/2]?'claimed':''}`} onClick={()=>draw('h',r/2,(c-1)/2)} aria-label="Draw horizontal edge"/>;return <>{c%2===0?<button key={c} className={`edge v ${edges.v[(r-1)/2][c/2]?'claimed':''}`} onClick={()=>draw('v',(r-1)/2,c/2)} aria-label="Draw vertical edge"/>:<span className="box-cell" key={c}>{boxes[((r-1)/2)*3+(c-1)/2]}</span>}</>;})}</div>)}</div></>}</div>;
}

export function MemoryMatch() {
  const values = ['A','A','B','B','C','C','D','D','E','E','F','F','G','G','H','H']; const shuffle = () => [...values].sort(()=>Math.random()-.5);
  const [cards,setCards]=useState(shuffle); const [open,setOpen]=useState<number[]>([]); const [matched,setMatched]=useState<number[]>([]); const [turns,setTurns]=useState(0); const [seconds,setSeconds]=useState(0);
  useEffect(()=>{if(open.length!==2)return undefined;const [a,b]=open;if(cards[a]===cards[b]){setMatched((m)=>[...m,a,b]);setOpen([]);return undefined;}const timer=window.setTimeout(()=>setOpen([]),650);return()=>window.clearTimeout(timer);},[open,cards]);
  useEffect(()=>{if(matched.length===16)return undefined;const timer=window.setInterval(()=>setSeconds((value)=>value+1),1000);return()=>window.clearInterval(timer);},[matched.length]);
  const reset=()=>{setCards(shuffle());setOpen([]);setMatched([]);setTurns(0);setSeconds(0);}; const done=matched.length===16;
  return <div>{done?<Result title="Board cleared." detail={`${turns} turns · ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}. Clean memory.`} onReplay={reset}/>:<><div className="status-line">{turns} turns · {Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')} · {matched.length/2} pairs found</div><div className="memory-board">{cards.map((card,i)=><button key={i} className={`memory-card ${open.includes(i)||matched.includes(i)?'flipped':''} ${matched.includes(i)?'matched':''}`} onClick={()=>{if(open.length<2&&!open.includes(i)&&!matched.includes(i)){setOpen((o)=>[...o,i]);if(open.length===1)setTurns((t)=>t+1);}}} aria-label={open.includes(i)||matched.includes(i)?`Card ${card}`:'Hidden card'} data-testid={`button-memory-${i}`}>{open.includes(i)||matched.includes(i)?card:'?'}</button>)}</div></>}</div>;
}

type Board2048 = number[][];
const empty2048=()=>Array.from({length:4},()=>Array(4).fill(0));
function addTile(board:Board2048){const spots: [number,number][]=[];board.forEach((row,r)=>row.forEach((v,c)=>{if(!v)spots.push([r,c]);}));if(spots.length){const [r,c]=spots[Math.floor(Math.random()*spots.length)];board[r][c]=Math.random()<.9?2:4;}return board;}
function slideLine(line:number[]){const values=line.filter(Boolean);let score=0;for(let i=0;i<values.length-1;i++)if(values[i]===values[i+1]){values[i]*=2;score+=values[i];values.splice(i+1,1);}while(values.length<4)values.push(0);return {line:values,score};}
export function Game2048(){
 const [board,setBoard]=useState(()=>addTile(addTile(empty2048())));const [score,setScore]=useState(0);const [best,setBest]=useState(()=>readNumber('2048-best'));const [over,setOver]=useState(false);
 const move=(direction:'left'|'right'|'up'|'down')=>{if(over)return;let next=board.map((r)=>[...r]);let gained=0;for(let i=0;i<4;i++){let line=direction==='left'||direction==='right'?[...next[i]]:next.map((r)=>r[i]);if(direction==='right'||direction==='down')line.reverse();const result=slideLine(line);if(direction==='right'||direction==='down')result.line.reverse();if(direction==='left'||direction==='right')next[i]=result.line;else result.line.forEach((v,j)=>next[j][i]=v);gained+=result.score;}if(JSON.stringify(next)!==JSON.stringify(board)){next=addTile(next);const total=score+gained;setBoard(next);setScore(total);if(total>best){setBest(total);saveNumber('2048-best',total);}if(!next.some((r)=>r.some((v)=>!v))||!next.some((r,rI)=>r.some((v,c)=>next[rI+1]?.[c]===v||next[rI]?.[c+1]===v)))setOver(true);}};
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const map:{[key:string]:'left'|'right'|'up'|'down'}={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',w:'up',a:'left',s:'down',d:'right',W:'up',A:'left',S:'down',D:'right'};if(map[e.key]){e.preventDefault();move(map[e.key]);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
 const reset=()=>{setBoard(addTile(addTile(empty2048())));setScore(0);setOver(false);}; return <div>{over||board.some((r)=>r.includes(2048))?<Result title={board.some((r)=>r.includes(2048))?'2048 reached.':'No more moves.'} detail={`Score ${score}. Best ${best}.`} onReplay={reset}/>:<><div className="status-line">Score {score}　·　Best {best}</div><div className="grid-2048">{board.flat().map((v,i)=><div key={i} className={`tile-2048 ${v?'v'+v:''}`}>{v||''}</div>)}</div><DirectionPad move={move}/></>}</div>;
}
function DirectionPad({move}:{move:(direction:'left'|'right'|'up'|'down')=>void}){return <div className="direction-pad"><button onClick={()=>move('up')} aria-label="Move up">↑</button><button onClick={()=>move('left')} aria-label="Move left">←</button><button onClick={()=>move('down')} aria-label="Move down">↓</button><button onClick={()=>move('right')} aria-label="Move right">→</button></div>;}

export function Snake(){
 const fresh=()=>({snake:[[8,8],[8,7],[8,6]],dir:[0,1] as [number,number],food:[4,5] as [number,number]});const [state,setState]=useState(fresh);const [score,setScore]=useState(0);const [best,setBest]=useState(()=>readNumber('snake-best'));const [over,setOver]=useState(false);
 const turn=(dir:[number,number])=>setState((s)=>({ ...s,dir: s.dir[0]===-dir[0]&&s.dir[1]===-dir[1]?s.dir:dir })); useEffect(()=>{const onKey=(e:KeyboardEvent)=>{const dirs:{[key:string]:[number,number]}={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]};if(dirs[e.key]){e.preventDefault();turn(dirs[e.key]);}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);});
 useEffect(()=>{if(over)return;const timer=window.setInterval(()=>setState((s)=>{const head:[number,number]=[s.snake[0][0]+s.dir[0],s.snake[0][1]+s.dir[1]];if(head[0]<0||head[0]>=16||head[1]<0||head[1]>=16||s.snake.some(([r,c])=>r===head[0]&&c===head[1])){setOver(true);return s;}const ate=head[0]===s.food[0]&&head[1]===s.food[1];let snake=[head,...s.snake];let food=s.food;if(ate){setScore((v)=>{const updated=v+1;if(updated>readNumber('snake-best')){saveNumber('snake-best',updated);setBest(updated);}return updated;});do{food=[Math.floor(Math.random()*16),Math.floor(Math.random()*16)] as [number,number];}while(snake.some(([r,c])=>r===food[0]&&c===food[1]));}else snake.pop();return {...s,snake,food};}),190);return()=>window.clearInterval(timer);},[over]);
 const reset=()=>{setState(fresh());setScore(0);setOver(false);};const steer=(direction:'left'|'right'|'up'|'down')=>{const vectors:{[key:string]:[number,number]}={up:[-1,0],down:[1,0],left:[0,-1],right:[0,1]};turn(vectors[direction]);};return <div>{over?<Result title="Wall met." detail={`Length ${state.snake.length}. Score ${score}. Best ${best}.`} onReplay={reset}/>:<><div className="status-line">Score {score}　·　Best {best}</div><div className="snake-board">{Array.from({length:256}).map((_,i)=>{const pos=[Math.floor(i/16),i%16];return <span key={i} className={`snake-cell ${state.snake.some(([r,c])=>r===pos[0]&&c===pos[1])?'snake':''} ${state.food[0]===pos[0]&&state.food[1]===pos[1]?'food':''}`}/>})}</div><DirectionPad move={steer}/></>}</div>;
}

const HANG_WORDS=['ARCADE','BRACKET','BUTTON','PUZZLE','PLAYER','SCORE','TURBO','JOYSTICK'];
export function Hangman(){const [word,setWord]=useState(()=>HANG_WORDS[Math.floor(Math.random()*HANG_WORDS.length)]);const [used,setUsed]=useState<string[]>([]);const misses=used.filter((l)=>!word.includes(l)).length;const won=word.split('').every((l)=>used.includes(l));const done=won||misses>=6;const reset=()=>{setWord(HANG_WORDS[Math.floor(Math.random()*HANG_WORDS.length)]);setUsed([]);};useEffect(()=>{const onKey=(event:KeyboardEvent)=>{const letter=event.key.toUpperCase();if(!done&&/^[A-Z]$/.test(letter)&&!used.includes(letter))setUsed((list)=>[...list,letter]);};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[done,used]);return <div>{done?<Result title={won?'Word found.':'Out of lines.'} detail={won?word:`The word was ${word}.`} onReplay={reset}/>:<><div className="status-line">{misses} / 6 misses</div><div className="hangman-word">{word.split('').map((letter,i)=><span className="hangman-letter" key={i}>{used.includes(letter)?letter:''}</span>)}</div><div className="letter-grid">{'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((letter)=><button key={letter} className={`letter-button ${used.includes(letter)?'used':''}`} disabled={used.includes(letter)} onClick={()=>setUsed((list)=>[...list,letter])} data-testid={`button-hangman-${letter}`}>{letter}</button>)}</div></>}</div>;}

export function ConnectFour(){const empty=()=>Array.from({length:6},()=>Array(7).fill(''));const [board,setBoard]=useState<string[][]>(empty);const [turn,setTurn]=useState<'R'|'Y'>('R');const [result,setResult]=useState<'R'|'Y'|'draw'|null>(null);const [pending,setPending]=useState<string[][]|null>(null);const [scores,setScores]=useState({you:0,house:0,draws:0});const win=(b:string[][],p:string)=>{for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const [dr,dc] of [[0,1],[1,0],[1,1],[1,-1]])if([0,1,2,3].every((n)=>b[r+dr*n]?.[c+dc*n]===p))return true;return false;};useEffect(()=>{if(!pending)return undefined;const timer=window.setTimeout(()=>{const options=pending[0].map((_,i)=>i).filter((i)=>!pending[0][i]);if(!options.length){setPending(null);return;}const choice=options[Math.floor(Math.random()*options.length)];const ai=pending.map((row)=>[...row]);for(let ar=5;ar>=0;ar--)if(!ai[ar][choice]){ai[ar][choice]='Y';break;}setBoard(ai);setPending(null);if(win(ai,'Y')){setResult('Y');setScores((s)=>({...s,house:s.house+1}));}else if(ai.every((row)=>row.every(Boolean))){setResult('draw');setScores((s)=>({...s,draws:s.draws+1}));}else setTurn('R');},280);return()=>window.clearTimeout(timer);},[pending]);const drop=(col:number)=>{if(result||turn!=='R')return;const next=board.map((r)=>[...r]);for(let r=5;r>=0;r--)if(!next[r][col]){next[r][col]='R';setBoard(next);if(win(next,'R')){setResult('R');setScores((s)=>({...s,you:s.you+1}));}else if(next.every((row)=>row.every(Boolean))){setResult('draw');setScores((s)=>({...s,draws:s.draws+1}));}else{setTurn('Y');setPending(next);}break;}};const reset=()=>{setBoard(empty());setTurn('R');setResult(null);setPending(null);};return <div>{result?<Result title={result==='R'?'Four in line.':result==='Y'?'Computer wins.':'Full board.'} detail={result==='draw'?'No spaces left.':`Score ${scores.you} — ${scores.house} · Draws ${scores.draws}`} onReplay={reset}/>:<><div className="status-line">You {scores.you}　·　House {scores.house}　·　Draws {scores.draws}　·　{turn==='R'?'Your turn':'Computer thinking'}</div><div className="connect-board">{board.flat().map((cell,i)=><button key={i} className={`connect-cell ${cell==='R'?'red':cell==='Y'?'yellow':''}`} onClick={()=>drop(i%7)} aria-label={`Column ${(i%7)+1}`} disabled={turn!=='R'} />)}</div></>}</div>;}

export function RockPaperScissors(){const choices=['ROCK','PAPER','SCISSORS'];const [you,setYou]=useState(0);const [house,setHouse]=useState(0);const [last,setLast]=useState('');const [done,setDone]=useState(false);const [lifetime,setLifetime]=useState(()=>readStats('rps-stats',{wins:0,losses:0,draws:0}));const play=(choice:string)=>{if(done)return;const computer=choices[Math.floor(Math.random()*3)];setLast(`${choice} / ${computer}`);const draw=choice===computer;const win=(choice==='ROCK'&&computer==='SCISSORS')||(choice==='PAPER'&&computer==='ROCK')||(choice==='SCISSORS'&&computer==='PAPER');if(draw)setLifetime((stats)=>{const updated={...stats,draws:stats.draws+1};saveStats('rps-stats',updated);return updated;});else if(win){setLifetime((stats)=>{const updated={...stats,wins:stats.wins+1};saveStats('rps-stats',updated);return updated;});setYou((v)=>{const next=v+1;if(next>=5)setDone(true);return next;});}else{setLifetime((stats)=>{const updated={...stats,losses:stats.losses+1};saveStats('rps-stats',updated);return updated;});setHouse((v)=>{const next=v+1;if(next>=5)setDone(true);return next;});}};const reset=()=>{setYou(0);setHouse(0);setLast('');setDone(false);};return <div>{done?<Result title={you>house?'You take the set.':'House takes the set.'} detail={`${you} — ${house}. Lifetime: ${lifetime.wins} wins · ${lifetime.losses} losses · ${lifetime.draws} draws.`} onReplay={reset}/>:<><div className="status-line">You {you}　·　House {house}　·　Lifetime {lifetime.wins}W / {lifetime.losses}L / {lifetime.draws}D{last?`　·　${last}`:''}</div><div className="rps-options">{choices.map((choice)=><button className="rps-choice" key={choice} onClick={()=>play(choice)}><b>{choice==='ROCK'?'■':choice==='PAPER'?'□':'△'}</b>{choice}</button>)}</div></>}</div>;}

export function NumberGuessing(){const [target,setTarget]=useState(()=>Math.floor(Math.random()*100)+1);const [value,setValue]=useState('');const [guesses,setGuesses]=useState<number[]>([]);const [message,setMessage]=useState('');const done=Number(value)===target;const submit=(event:FormEvent)=>{event.preventDefault();const number=Number(value);if(!number||number<1||number>100){setMessage('Use a number from 1 to 100.');return;}setGuesses((g)=>[...g,number]);setMessage(number===target?'You found the signal.':number>target?'Lower.':'Higher.');if(number===target)setValue('');};const reset=()=>{setTarget(Math.floor(Math.random()*100)+1);setValue('');setGuesses([]);setMessage('');};const hint=guesses.length>=4?(target%2===0?'Hint: the number is even.':'Hint: the number is odd.'):'';return <div className="guess-wrap">{done?<Result title="Signal found." detail={`${guesses.length} ${guesses.length===1?'guess':'guesses'} to lock on.`} onReplay={reset}/>:<><div className="guess-number">?</div><p className="status-line">{message||hint||'A number from 1 to 100 is hiding here.'}</p><form onSubmit={submit}><input className="guess-input" type="number" value={value} onChange={(e)=>setValue(e.target.value)} placeholder="Your guess" aria-label="Your number guess" data-testid="input-number-guess" /><button className="button button-primary" style={{marginTop:'.8rem',width:'100%'}} type="submit" data-testid="button-submit-guess">Lock it in →</button></form><p className="muted" style={{fontSize:'.8rem'}}>{guesses.length} guesses made</p></>}</div>;}

export function GameInstructions({ children }: { children: ReactNode }) { return <>{children}</>; }